buseta_taller_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BusetaTallerBundle:Default:index }

taller_principal:
    pattern:  /modulo/taller
    defaults: { _controller: "BusetaTallerBundle:Default:principal" }

mantenimientopreventivo:
    resource: @BusetaTallerBundle/Controller/MantenimientoPreventivoController.php
    type: annotation

buseta_taller_observacion:
    resource: "@BusetaTallerBundle/Controller/ObservacionController.php"
    type: annotation
