core_homepage:
    pattern:  /
    defaults: { _controller: CoreBundle:Default:index }

configuracion_principal:
    pattern:  /modulo/configuracion
    defaults: { _controller: "CoreBundle:Default:principal" }

coreBundle_cambiohorasistema:
    resource: "@CoreBundle/Resources/config/routing/cambiohorasistema.yml"
    prefix:   /cambiohorasistema

coreBundle_fechasistema:
    resource: "@CoreBundle/Resources/config/routing/fechasistema.yml"
    prefix:   /fechaistema