imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: security_conf.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        version_sistema: beta4
    form:
        resources: ['BusetaTemplateBundle:Form:fields.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['BusetaBodegaBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#admingenerator_generator:
#    base_admin_template: AdmingeneratorGeneratorBundle::base_admin_assetic_less.html.twig
#    use_propel: false
#    use_doctrine_orm: true
#    use_doctrine_odm: false
#    dashboard_welcome_path: my_dashboard_welcome
#    twig:
#      number_format:
#        decimal:              2
#        decimal_point:        .

knp_menu:
    twig: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: HatueySoft\SecurityBundle\Entity\User

knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: CoreBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: CoreBundle:Pagination:sortable_link.html.twig # sort link template

#liip_imagine:
#    resolvers:
#        default:
#            web_path:
#                web_root:     %kernel.root_dir%/web/images
#                cache_prefix: media/cache
#
#    #driver:               gd
#    cache:                default
#    #data_loader:          default
#    #controller_actdion:    liip_imagine.controller:filterAction
#    filter_sets:
#        my_thumb_in:
#            filters:
#                thumbnail: { size: [32, 32], mode: inset } # Transforms 50x40 to 32x26, no cropping

easy_admin:
    site_name: 'Nomencladores'
    list_actions: ['show', 'edit', 'delete']
    assets:
        css:
            - %nomenclator.assets.css%
    entities:
        'Aceite Caja Cambios': Buseta\NomencladorBundle\Entity\AceiteCajaCambios
        'Aceite Hidráulico': Buseta\NomencladorBundle\Entity\AceiteHidraulico
        'Acite Motor': Buseta\NomencladorBundle\Entity\AceiteMotor
        'Aceite Transmisión': Buseta\NomencladorBundle\Entity\AceiteTransmision
        'Caja Chica': Buseta\NomencladorBundle\Entity\CajaChica
        'Color': Buseta\NomencladorBundle\Entity\Color
        'Combustible': Buseta\NomencladorBundle\Entity\Combustible
        'Condición': Buseta\NomencladorBundle\Entity\Condicion
        'Estilo': Buseta\NomencladorBundle\Entity\Estilo
        'EstadoCivil': Buseta\NomencladorBundle\Entity\EstadoCivil
        'Forma Pago': Buseta\NomencladorBundle\Entity\FormaPago
        'Garantía Tarea': Buseta\NomencladorBundle\Entity\GarantiaTarea
        'Grupo': Buseta\NomencladorBundle\Entity\Grupo
        'Subgrupo': Buseta\NomencladorBundle\Entity\Subgrupo
        'Mantenimiento % Cumplido': Buseta\NomencladorBundle\Entity\MantenimientoPorcientoCumplido
        'Marca': Buseta\NomencladorBundle\Entity\Marca
        'Modelo': Buseta\NomencladorBundle\Entity\Modelo
        'Marca Motor': Buseta\NomencladorBundle\Entity\MarcaMotor
        'Moneda': Buseta\NomencladorBundle\Entity\Moneda
        'Nacionalidad': Buseta\NomencladorBundle\Entity\Nacionalidad
        'Prioridad solicitud': Buseta\NomencladorBundle\Entity\PrioridadSolicitud
        'Tipo Compra': Buseta\NomencladorBundle\Entity\TipoCompra
        'Tipo Contacto': Buseta\NomencladorBundle\Entity\TipoContacto
        'Tarea': Buseta\NomencladorBundle\Entity\Tarea
        'Unidad de Medida': Buseta\NomencladorBundle\Entity\UOM
        'Medio Reporte': Buseta\NomencladorBundle\Entity\MedioReporte

#HATUEY SOFT SECURITY CONFIGURATION
hatuey_soft_security:
    security_config: "%kernel.root_dir%/config/security_conf.yml"
    command_scope: "%kernel.root_dir%"
    acl:
        entities:
            reporte: Buseta\TallerBundle\Entity\Reporte
            diagnostico: Buseta\TallerBundle\Entity\Diagnostico
            ordentrabajo: Buseta\TallerBundle\Entity\OrdenTrabajo


#EJEMPLO DE COMO OBTENER LOS VALORES DEL ARCHIVO "CONFIG.YML"
    #$sequences_values = $this->get('service_container')->getParameter('hatuey_soft_sequence');
        #var_dump($sequences_values['producto_seq']);
        #var_dump($sequences_values['bodega_seq']);

hatuey_soft_sequence:
    sequences:
#        producto_seq:   Buseta\BodegaBundle\Entity\Producto
#        bodega_seq:     Buseta\BodegaBundle\Entity\Bodega
#        tercero_seq:    Buseta\BodegaBundle\Entity\Tercero
        reporte_seq:    Buseta\TallerBundle\Entity\Reporte

hatuey_soft_menu:
    menu_conf: "%kernel.root_dir%/config/menu_conf.yml"
    menu_name: menu
