imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: security_conf.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        version_sistema: alpha_v1
    form:
        resources: ['BusetaTemplateBundle:Form:fields.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['BusetaBodegaBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#admingenerator_generator:
#    base_admin_template: AdmingeneratorGeneratorBundle::base_admin_assetic_less.html.twig
#    use_propel: false
#    use_doctrine_orm: true
#    use_doctrine_odm: false
#    dashboard_welcome_path: my_dashboard_welcome
#    twig:
#      number_format:
#        decimal:              2
#        decimal_point:        .

knp_menu:
    twig: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: HatueySoft\SecurityBundle\Entity\User

knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: CoreBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: CoreBundle:Pagination:sortable_link.html.twig # sort link template

#liip_imagine:
#    resolvers:
#        default:
#            web_path:
#                web_root:     %kernel.root_dir%/web/images
#                cache_prefix: media/cache
#
#    #driver:               gd
#    cache:                default
#    #data_loader:          default
#    #controller_actdion:    liip_imagine.controller:filterAction
#    filter_sets:
#        my_thumb_in:
#            filters:
#                thumbnail: { size: [32, 32], mode: inset } # Transforms 50x40 to 32x26, no cropping

easy_admin:
    site_name: 'Nomencladores'
    list_actions: ['show', 'edit', 'delete']
    entities:
        aceiteCajaCambios:
            class: Buseta\NomencladorBundle\Entity\AceiteCajaCambios
            label: 'Aceite Caja Cambios'
        aceiteHidraulico:
            class: Buseta\NomencladorBundle\Entity\AceiteHidraulico
            label: 'Aceite Hidráulico'
        aceiteMotor:
            class: Buseta\NomencladorBundle\Entity\AceiteMotor
            label: 'Acite Motor'
        aceiteTransision:
            class: Buseta\NomencladorBundle\Entity\AceiteTransmision
            label: 'Aceite Transmisión'
        cajaChica:
            class: Buseta\NomencladorBundle\Entity\CajaChica
            label: 'Caja Chica'
        color:
            class: Buseta\NomencladorBundle\Entity\Color
            label: 'Color'
        condicionesPago:
            class: Buseta\TallerBundle\Entity\CondicionesPago
            label: 'Condiciones Pago'
        combustible:
            class: Buseta\NomencladorBundle\Entity\Combustible
            label: 'Combustible'
        condicion:
            class: Buseta\NomencladorBundle\Entity\Condicion
            label: 'Condición Producto'
        estilo:
            class: Buseta\NomencladorBundle\Entity\Estilo
            label: 'Estilo'
        estadoCivil:
            class: Buseta\NomencladorBundle\Entity\EstadoCivil
            label: 'Estado Civil'
        formaPago:
            class: Buseta\NomencladorBundle\Entity\FormaPago
            label: 'Forma Pago'
        garantiaTarea:
            class: Buseta\NomencladorBundle\Entity\GarantiaTarea
            label: 'Garantía Tarea'
        grupo:
            class: Buseta\NomencladorBundle\Entity\Grupo
            label: 'Grupo'
        subgrupo:
            class: Buseta\NomencladorBundle\Entity\Subgrupo
            label: 'Subgrupo'
        impuesto:
            class: Buseta\TallerBundle\Entity\Impuesto
            label: 'Impuesto'
            list:
                fields:
                    - 'nombre'
                    - { property: 'numero', label: 'Número' }
                    - { property: 'tipo' }
                    - 'tarifa'
            show:
                fields:
                    - 'nombre'
                    - { property: 'numero', label: 'Número' }
                    - 'tipo'
                    - 'tarifa'
            new:
                fields:
                    - 'nombre'
                    - { property: 'numero', label: 'Número' }
                    - { property: 'tipo', type: 'choice', type_options: { placeholder: '---Seleccione---', choices: {fijo: 'Fijo', porcentaje: 'Porcentaje (%)' } } }
                    - { property: 'tarifa', type: 'number', format: '%.2f' }
            edit:
                fields:
                    - 'nombre'
                    - { property: 'numero', label: 'Número' }
                    - { property: 'tipo', type: 'choice', type_options: { placeholder: '---Seleccione---', choices: {fijo: 'Fijo', porcentaje: 'Porcentaje (%)' } } }
                    - { property: 'tarifa', type: 'number', format: '%.2f' }
        mantenimientoPorcientoCumplido:
            class: Buseta\NomencladorBundle\Entity\MantenimientoPorcientoCumplido
            label: 'Mantenimiento % Cumplido'
        marca:
            class: Buseta\NomencladorBundle\Entity\Marca
            label: 'Marca'
        modelo:
            class: Buseta\NomencladorBundle\Entity\Modelo
            label: 'Modelo'
        marcaMotor:
            class: Buseta\NomencladorBundle\Entity\MarcaMotor
            label: 'Marca Motor'
        moneda:
            class: Buseta\NomencladorBundle\Entity\Moneda
            label: 'Moneda'
        nacionalidad:
            class: Buseta\NomencladorBundle\Entity\Nacionalidad
            label: 'Nacionalidad'
        prioridadSolicitud:
            class: Buseta\NomencladorBundle\Entity\PrioridadSolicitud
            label: 'Prioridad Solicitud'
        tiempoPrioridad:
            class: Buseta\NomencladorBundle\Entity\TiempoPrioridad
            label: 'Tiempo Prioridad'
            list:
                fields:
                    - 'id'
                    - 'valor'
                    - 'minutos'
                    - { property: 'colorentiempo', label: 'Color en Tiempo' }
                    - { property: 'coloratrasado', label: 'Color si Atrasado' }
        tipoCompra:
            class: Buseta\NomencladorBundle\Entity\TipoCompra
            label: 'Tipo Compra'
        tipoContacto:
            class: Buseta\NomencladorBundle\Entity\TipoContacto
            label: 'Tipo Contacto'
        tarea:
            class: Buseta\NomencladorBundle\Entity\Tarea
            label: 'Tarea'
        uom:
            class: Buseta\NomencladorBundle\Entity\UOM
            label: 'Unidad de Medida'
        medioReporte:
            class: Buseta\NomencladorBundle\Entity\MedioReporte
            label: 'Medio Reporte'

#HATUEY SOFT SECURITY CONFIGURATION
hatuey_soft_security:
    acl:
        symfony_acl: false
        entities:
            reporte: Buseta\TallerBundle\Entity\Reporte
            diagnostico: Buseta\TallerBundle\Entity\Diagnostico
            ordentrabajo: Buseta\TallerBundle\Entity\OrdenTrabajo
#            reporte:
#                    class: Buseta\TallerBundle\Entity\Reporte
#                    label: 'Reporte de Transacciones'
#                    rules:
#                             - !
#                             - { code: 'aa', icon: 'book' }
#                             - { code: 'cc' }
#                             - { code: 'show' }
#            trabajador:
#                    class: Buseta\TallerBundle\Entity\Trabajador
#                    label: 'Trabajador de Planilla'
#                    rules:
#                             - { code: pasaraborrador, icon: 'book' }
#                             - { code: 'cc' }
#                             - { code: '!show' }
#            diagnostico:
#                    class: Buseta\TallerBundle\Entity\Diagnostico
#                    rules: [ terminar , delete , { code: 'list', label: 'LISTADOOOOOOO',  icon: 'leaf' } ]
#            ordentrabajo:
#                    class: Buseta\TallerBundle\Entity\OrdenTrabajo
#                    rules: [ !list , !search ]
#            bodega:
#                    class: Buseta\BodegaBundle\Entity\Bodega
#                    rules: []
#            almacen:
#                    class: Buseta\BodegaBundle\Entity\Almacen
#            usuario: Buseta\TallerBundle\Entity\Usuario

#    acl:
#        entities:
#            reporte: Buseta\TallerBundle\Entity\Reporte
#            diagnostico: Buseta\TallerBundle\Entity\Diagnostico
#            ordentrabajo: Buseta\TallerBundle\Entity\OrdenTrabajo


#EJEMPLO DE COMO OBTENER LOS VALORES DEL ARCHIVO "CONFIG.YML"
    #$sequences_values = $this->get('service_container')->getParameter('hatuey_soft_sequence');
        #var_dump($sequences_values['producto_seq']);
        #var_dump($sequences_values['bodega_seq']);

hatuey_soft_sequence:
    sequences:
#        producto_seq:   Buseta\BodegaBundle\Entity\Producto
#        bodega_seq:     Buseta\BodegaBundle\Entity\Bodega
#        tercero_seq:    Buseta\BodegaBundle\Entity\Tercero
        reporte_seq:     Buseta\TallerBundle\Entity\Reporte
        diagnostico_seq: Buseta\TallerBundle\Entity\Diagnostico
        ot_seq:          Buseta\TallerBundle\Entity\OrdenTrabajo
        necesidad_material_seq: Buseta\BodegaBundle\Entity\NecesidadMaterial
        registro_compra_seq: Buseta\BodegaBundle\Entity\PedidoCompra
        orden_entrada_seq: Buseta\BodegaBundle\Entity\Albaran

hatuey_soft_menu:
    menu_conf: "%kernel.root_dir%/config/menu_conf.yml"
    menu_name: menu

# GLOBAL SERVICES
services:
    fos_user.doctrine_registry:
        alias: doctrine
