BusetaTallerBundle_tareaadicional:
        resource: "@BusetaTallerBundle/Resources/config/routing/tareaadicional.yml"
        prefix:   /tareaadicional

BusetaTallerBundle_ordentrabajo:
        resource: "@BusetaTallerBundle/Resources/config/routing/ordentrabajo.yml"
        prefix:   /ordentrabajo

BusetaTallerBundle_reporte:
        resource: "@BusetaTallerBundle/Resources/config/routing/reporte.yml"
        prefix:   /reporte

BusetaTallerBundle_diagnostico:
        resource: "@BusetaTallerBundle/Resources/config/routing/diagnostico.yml"
        prefix:   /diagnostico

BusetaTallerBundle_observacion:
        resource: "@BusetaTallerBundle/Resources/config/routing/observacion.yml"
        prefix:   /observacion

BusetaTallerBundle_observaciondiagnostico:
        resource: "@BusetaTallerBundle/Resources/config/routing/observaciondiagnostico.yml"
        prefix:   /observaciondiagnostico

BusetaTallerBundle_tareamantenimiento:
        resource: "@BusetaTallerBundle/Resources/config/routing/tareamantenimiento.yml"
        prefix:   /tareamantenimiento

BusetaTallerBundle_condicionespago:
        resource: "@BusetaTallerBundle/Resources/config/routing/condicionespago.yml"
        prefix:   /condicionespago

BusetaTallerBundle_pedidocompralinea:
        resource: "@BusetaBodegaBundle/Resources/config/routing/pedido_compra_linea.yml"
        prefix:   /pedidocompralinea

BusetaTallerBundle_pedidocompra:
        resource: "@BusetaBodegaBundle/Resources/config/routing/pedidocompra.yml"
        prefix:   /pedidocompra

BusetaTallerBundle_inventariofisico:
        resource: "@BusetaBodegaBundle/Resources/config/routing/inventariofisico.yml"
        prefix:   /inventariofisico

BusetaTallerBundle_necesidadmateriallinea:
        resource: "@BusetaBodegaBundle/Resources/config/routing/necesidad_material_linea.yml"
        prefix:   /necesidadmateriallinea

BusetaTallerBundle_necesidadmaterial:
        resource: "@BusetaBodegaBundle/Resources/config/routing/necesidadmaterial.yml"
        prefix:   /necesidadmaterial

BusetaTallerBundle_precioproducto:
        resource: "@BusetaBodegaBundle/Resources/config/routing/precio_producto.yml"
        prefix:   /precioproducto

BusetaTallerBundle_albaran:
        resource: "@BusetaBodegaBundle/Resources/config/routing/albaran.yml"
        prefix:   /albaran

BusetaTallerBundle_albaranlinea:
        resource: "@BusetaBodegaBundle/Resources/config/routing/albaran_linea.yml"
        prefix:   /albaranlinea

BusetaTallerBundle_impuesto:
        resource: "@BusetaTallerBundle/Resources/config/routing/impuesto.yml"
        prefix:   /impuesto

buseta_template:
    resource: "@BusetaTemplateBundle/Resources/config/routing.yml"
    prefix:   /

BusetaBodegaBundle_producto:
        resource: "@BusetaBodegaBundle/Resources/config/routing/producto.yml"
        prefix:   /bodega/producto

BusetaBodegaBundle_movimiento:
        resource: "@BusetaBodegaBundle/Resources/config/routing/movimiento.yml"
        prefix:   /bodega/movimiento

BusetaBodegaBundle_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing/bodega.yml"
    prefix:   /bodega

BusetaBodegaBundle_categoria_producto:
    resource: "@BusetaBodegaBundle/Resources/config/routing/categoria_producto.yml"
    prefix:   /bodega/categoria_producto

BusetaBodegaBundle_tercero:
    resource: "@BusetaBodegaBundle/Resources/config/routing/tercero.yml"
    prefix:   /bodega/tercero

BusetaTallerBundle_informestock:
        resource: "@BusetaBodegaBundle/Resources/config/routing/informe_stock.yml"
        prefix:   /informestock

buseta_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing.yml"

buseta_taller:
    resource: "@BusetaTallerBundle/Resources/config/routing.yml"

buseta_buses:
    resource: "@BusetaBusesBundle/Resources/config/routing.yml"

buseta_security:
    resource: "@BusetaSecurityBundle/Resources/config/routing.yml"

core:
    resource: "@CoreBundle/Resources/config/routing.yml"

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /data

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /nomenclador

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#_imagine:
#    resource: .
#    type:     imagine
