BusetaTallerBundle_tareaadicional:
        resource: "@BusetaTallerBundle/Resources/config/routing/tareaadicional.yml"
        prefix:   /tareaadicional

BusetaTallerBundle_ordentrabajo:
        resource: "@BusetaTallerBundle/Resources/config/routing/ordentrabajo.yml"
        prefix:   /ordentrabajo

BusetaTallerBundle_tareamantenimiento:
        resource: "@BusetaTallerBundle/Resources/config/routing/tareamantenimiento.yml"
        prefix:   /tareamantenimiento
        
BusetaTallerBundle_condicionespago:
        resource: "@BusetaTallerBundle/Resources/config/routing/condicionespago.yml"
        prefix:   /condicionespago

BusetaTallerBundle_pedidocompralinea:
        resource: "@BusetaBodegaBundle/Resources/config/routing/pedido_compra_linea.yml"
        prefix:   /pedidocompralinea

BusetaTallerBundle_pedidocompra:
        resource: "@BusetaBodegaBundle/Resources/config/routing/pedidocompra.yml"
        prefix:   /pedidocompra

BusetaTallerBundle_albaran:
        resource: "@BusetaBodegaBundle/Resources/config/routing/albaran.yml"
        prefix:   /albaran

BusetaTallerBundle_albaranlinea:
        resource: "@BusetaBodegaBundle/Resources/config/routing/albaran_linea.yml"
        prefix:   /albaranlinea

BusetaTallerBundle_impuesto:
        resource: "@BusetaTallerBundle/Resources/config/routing/impuesto.yml"
        prefix:   /impuesto

buseta_template:
    resource: "@BusetaTemplateBundle/Resources/config/routing.yml"
    prefix:   /

BusetaBodegaBundle_producto:
        resource: "@BusetaBodegaBundle/Resources/config/routing/producto.yml"
        prefix:   /bodega/producto

BusetaBodegaBundle_movimiento:
        resource: "@BusetaBodegaBundle/Resources/config/routing/movimiento.yml"
        prefix:   /bodega/movimiento

BusetaBodegaBundle_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing/bodega.yml"
    prefix:   /bodega

BusetaBodegaBundle_direccion:
    resource: "@BusetaBodegaBundle/Resources/config/routing/direccion.yml"
    prefix:   /bodega/direccion

BusetaBodegaBundle_tercero:
    resource: "@BusetaBodegaBundle/Resources/config/routing/tercero.yml"
    prefix:   /bodega/tercero

BusetaTallerBundle_informestock:
        resource: "@BusetaBodegaBundle/Resources/config/routing/informe_stock.yml"
        prefix:   /informestock

buseta_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing.yml"
    prefix:   /

buseta_taller:
    resource: "@BusetaTallerBundle/Resources/config/routing.yml"
    prefix:   /

buseta_buses:
    resource: "@BusetaBusesBundle/Resources/config/routing.yml"
    prefix:   /

buseta_security:
    resource: "@BusetaSecurityBundle/Resources/config/routing.yml"
    prefix:   /

_welcome_dashboard:
    resource: "@BusetaNomencladorBundle/Resources/config/routing.yml"
    prefix:   /admin/nomenclador

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /data

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /nomenclador

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#_imagine:
#    resource: .
#    type:     imagine