buseta_combustible:
    resource: "@BusetaCombustibleBundle/Resources/config/routing.yml"
    prefix:   /

buseta_template:
    resource: "@BusetaTemplateBundle/Resources/config/routing.yml"
    prefix:   /

buseta_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing.yml"

buseta_taller:
    resource: "@BusetaTallerBundle/Resources/config/routing.yml"

buseta_buses:
    resource: "@BusetaBusesBundle/Resources/config/routing.yml"

buseta_security:
    resource: "@BusetaSecurityBundle/Resources/config/routing.yml"
    prefix:   /security

core:
    resource: "@CoreBundle/Resources/config/routing.yml"

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /data

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /nomenclador

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
