security:
    access_decision_manager:
        strategy:             affirmative

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512
            iterations: 1000


    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, in_memory]
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false
        secured_area:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_provider: form.csrf_provider
            logout: ~
            anonymous: ~
            http_basic: ~
