categoria_producto:
    path:  /
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:index" }

categoria_producto_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:show" }

categoria_producto_new:
    path:  /new
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:new" }

categoria_producto_create:
    path:  /create
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:create" }
    requirements: { methods: post }
    options:
        expose: true

categoria_producto_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:edit" }

categoria_producto_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:update" }
    requirements: { methods: post|put }

categoria_producto_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:CategoriaProducto:delete" }
    requirements: { methods: post|delete }
