movimiento:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:index" }

movimiento_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:show" }

movimiento_new:
    pattern:  /new
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:new" }

movimiento_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:create" }
    requirements: { _method: post }

movimiento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:edit" }

movimiento_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:update" }
    requirements: { _method: post|put }

movimiento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:delete" }
    requirements: { _method: post|delete }

movimientos_productos_create:
    pattern:  /movimientos/create
    defaults: { _controller: "BusetaBodegaBundle:Movimiento:create_movimiento" }
    requirements: { _method: post }

movimientos_ajax_almacenOrigen_almacenDestino:
  pattern: /select_almacenOrigen_almacenDestino
  defaults: { _controller: "BusetaBodegaBundle:Movimiento:select_almacenOrigen_almacenDestino" }
  requirements: { _method: "GET" }
  options:
      expose: true

movimiento_informe:
    pattern:  /informeMovimiento
    defaults: { _controller: "BusetaBodegaBundle:Informe:informeMovimientos" }

movimiento_ajax_busqueda_avanzada:
  pattern: /busqueda-avanzada/{page}/{cantResult}
  defaults: { _controller: "BusetaBodegaBundle:Informe:busquedaAvanzada", page: 0, cantResult: 10 }
  requirements: { _method: "GET" }