BusetaBodegaBundle_bitacoraalmacen:
    resource: "@BusetaBodegaBundle/Resources/config/routing/bitacoraalmacen.yml"
    prefix:   /bodega/bitacoraalmacen

BusetaBodegaBundle_necesidadmaterial:
    resource: "@BusetaBodegaBundle/Resources/config/routing/necesidadmaterial.yml"
    prefix:   /necesidadmaterial

BusetaBodegaBundle_inventariofisico:
    resource: "@BusetaBodegaBundle/Resources/config/routing/inventariofisico.yml"
    prefix:   /inventariofisico

BusetaBodegaBundle_necesidadmateriallinea:
    resource: "@BusetaBodegaBundle/Resources/config/routing/necesidad_material_linea.yml"
    prefix:   /necesidadmateriallinea

BusetaBodegaBundle_producto:
    resource: "@BusetaBodegaBundle/Resources/config/routing/producto.yml"
    prefix:   /bodega/producto

BusetaBodegaBundle_movimiento:
    resource: "@BusetaBodegaBundle/Resources/config/routing/salidabodega.yml"
    prefix:   /bodega/salidabodega

BusetaBodegaBundle_salidabodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing/movimiento.yml"
    prefix:   /bodega/movimiento

BusetaBodegaBundle_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing/bodega.yml"
    prefix:   /bodega

BusetaBodegaBundle_categoria_producto:
    resource: "@BusetaBodegaBundle/Resources/config/routing/categoria_producto.yml"
    prefix:   /bodega/categoria_producto

BusetaBodegaBundle_informestock:
    resource: "@BusetaBodegaBundle/Resources/config/routing/informe_stock.yml"
    prefix:   /informestock

BusetaBodegaBundle_precioproducto:
    resource: "@BusetaBodegaBundle/Resources/config/routing/precio_producto.yml"
    prefix:   /precioproducto

#BusetaBodegaBundle_albaran:
#    resource: "@BusetaBodegaBundle/Resources/config/routing/albaran.yml"
#    prefix:   /albaran
#
#BusetaBodegaBundle_albaranlinea:
#    resource: "@BusetaBodegaBundle/Resources/config/routing/albaran_linea.yml"
#    prefix:   /albaranlinea

bodega_principal:
  pattern:  /modulo/bodega
  defaults: { _controller: "BusetaBodegaBundle:Bodega:principal" }

bodega_informe_stock:
  pattern:  /modulo/bodega/informe_stock
  defaults: { _controller: "BusetaBodegaBundle:InformeStock:index" }

bodega_informe_costos:
  pattern:  /modulo/bodega/informe_costos
  defaults: { _controller: "BusetaBodegaBundle:Informe:informeCostos" }

buseta_bodega_terceros:
  resource: "@BusetaBodegaBundle/Controller/TerceroController.php"
  type:     annotation

buseta_bodega_persona:
  resource: "@BusetaBodegaBundle/Controller/PersonaController.php"
  type:     annotation

bodega_proveedor:
    resource: "@BusetaBodegaBundle/Controller/ProveedorController.php"
    type:     annotation

bodega_index:
    resource: "@BusetaBodegaBundle/Controller/BodegaController.php"
    type:     annotation

bodega_direccion:
    resource: "@BusetaBodegaBundle/Controller/DireccionController.php"
    type:     annotation

bodega_mecanismo_contacto:
    resource: "@BusetaBodegaBundle/Controller/MecanismoContactoController.php"
    type:     annotation

bodega_persona_contacto:
    resource: "@BusetaBodegaBundle/Controller/PersonaContactoController.php"
    type:     annotation

buseta_bodega_pedidocompra:
  resource: "@BusetaBodegaBundle/Controller/PedidoCompraController.php"
  type:     annotation

buseta_bodega_pedidocompralinea:
  resource: "@BusetaBodegaBundle/Controller/PedidoCompraLineaController.php"
  type:     annotation

buseta_bodega_inventariofisico:
    resource: "@BusetaBodegaBundle/Controller/InventarioFisicoController.php"
    type: annotation

buseta_bodega_inventariofisicolinea:
    resource: "@BusetaBodegaBundle/Controller/InventarioFisicoLineaController.php"
    type: annotation

buseta_bodega_necesidadmaterial:
  resource: "@BusetaBodegaBundle/Controller/NecesidadMaterialController.php"
  type:     annotation

# ALBARAN
buseta_bodega_albaran:
    resource: "@BusetaBodegaBundle/Controller/AlbaranController.php"
    type: annotation

buseta_bodega_albaranlinea:
    resource: "@BusetaBodegaBundle/Controller/AlbaranLineaController.php"
    type: annotation

buseta_bodega_producto:
    resource: "@BusetaBodegaBundle/Controller/ProductoController.php"
    type: annotation

buseta_bodega_salidabodega:
    resource: "@BusetaBodegaBundle/Controller/SalidaBodegaController.php"
    type: annotation

buseta_bodega_necesidadmateriallinea:
  resource: "@BusetaBodegaBundle/Controller/NecesidadMaterialLineaController.php"
  type:     annotation

buseta_bodega_movimientosproductos:
  resource: "@BusetaBodegaBundle/Controller/MovimientoProductosController.php"
  type:     annotation

buseta_bodega_salidabodega_productos:
  resource: "@BusetaBodegaBundle/Controller/SalidaBodegaProductoController.php"
  type:     annotation

buseta_bodega_productoprecio:
    resource: "@BusetaBodegaBundle/Controller/PrecioProductoController.php"
    type: annotation

buseta_bodega_productocosto:
    resource: "@BusetaBodegaBundle/Controller/CostoProductoController.php"
    type: annotation

buseta_bodega_categoriaproducto:
    resource: "@BusetaBodegaBundle/Controller/CategoriaProductoController.php"
    type: annotation
