parameters:
    consecutivoCompra: 89

services:
    # hidden_entity Form Type
    form.type.hidden_entity:
        class: Buseta\BodegaBundle\Form\Type\HiddenEntityType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: hidden_entity }

    bodega.movimiento.type:
        class: Buseta\BodegaBundle\Form\Type\MovimientoType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'buseta_bodegabundle_movimiento'}
    bodega.necesidad.type:
        class: Buseta\BodegaBundle\Form\Type\NecesidadMaterialType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_necesidad_material'}
    bodega.compra.type:
        class: Buseta\BodegaBundle\Form\Type\PedidoCompraType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_pedido_compra'}
    bodega.albaran.type:
        class: Buseta\BodegaBundle\Form\Type\AlbaranType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_albaran_type'}
    buseta_pedidocompra.linea.handler:
        class: Buseta\BodegaBundle\Form\Handler\PedidoCompraLineaHandler
        arguments:
            - @service_container
    buseta_inventariofisico.linea.handler:
        class: Buseta\BodegaBundle\Form\Handler\InventarioFisicoLineaHandler
        arguments:
            - @service_container
    bodega.nececidad.type:
        class: Buseta\BodegaBundle\Form\Type\NecesidadMaterialType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_necesidad_material'}
    buseta_necesidadmaterial.linea.handler:
        class: Buseta\BodegaBundle\Form\Handler\NecesidadMaterialLineaHandler
        arguments:
            - @service_container
    buseta_albaran.linea.handler:
        class: Buseta\BodegaBundle\Form\Handler\AlbaranLineaHandler
        arguments:
            - @service_container
    bodega.producto.type:
        class: Buseta\BodegaBundle\Form\Type\ProductoType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_producto'}
    bodega.inventariofisico.type:
        class: Buseta\BodegaBundle\Form\Type\InventarioFisicoType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'bodega_inventariofisico_type'}
    buseta_producto.precio.handler:
      class: Buseta\BodegaBundle\Form\Handler\PrecioProductoHandler
      arguments:
        - @service_container
    buseta_producto.costo.handler:
      class: Buseta\BodegaBundle\Form\Handler\CostoProductoHandler
      arguments:
        - @service_container
    # MANAGERS
    buseta.bodega.terceros_manager:
      class: Buseta\BodegaBundle\Manager\TerceroManager
      arguments:
        - @doctrine.orm.entity_manager
        - @session
        - @translator
        - @logger
