parameters:
#    data.example.class: Buseta\DataBundle\Example

services:
    handlebuses:
        class: Buseta\BusesBundle\Handle\HandleAutobus
        arguments: [@doctrine.orm.entity_manager]

    # FORM TYPES
    buses.buses_autobus.type:
        class: Buseta\BusesBundle\Form\Type\AutobusBasicoType
        arguments: [@security.authorization_checker]
        tags:
            - {name: form.type, alias: 'buses_autobus_basico'}
    buses.buses_vehiculo.type:
        class: Buseta\BusesBundle\Form\Type\VehiculoType
        arguments: [@security.authorization_checker]
        tags:
            - {name: form.type, alias: 'buses_vehiculo'}
    buses.buses_chofer.type:
        class: Buseta\BusesBundle\Form\Type\ChoferType
        tags:
            - {name: form.type, alias: 'buses_chofer'}
    buses.buses_autobus_extra.type:
        class: Buseta\BusesBundle\Form\Type\InformacionExtraType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'buses_autobus_informacion_extra'}
    buses.buses_autobus_filtro.type:
        class: Buseta\BusesBundle\Form\Type\FiltroType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'buses_autobus_filtro'}
    buses.buses_autobus_imagenes.type:
        class: Buseta\BusesBundle\Form\Type\ImagenType
        arguments: [@doctrine.orm.entity_manager, @service_container]
        tags:
            - {name: form.type, alias: 'buses_autobus_imagenes'}

#VALIDATORS
    buses.capacidad_tanque.validador:
        class: Buseta\BusesBundle\Validator\Constraints\CapacidadTanqueValidoValidator
        tags:
            - {name: validator.constraint_validator, alias: capacidadTanque_validador}
